// ─── Permisos del sistema ────────────────────────────────────────────────────
export const PERMISOS = {
  // Dashboard
  verDashboard:          'verDashboard',
  // Vehículos
  verVehiculos:          'verVehiculos',
  crearVehiculos:        'crearVehiculos',
  eliminarVehiculos:     'eliminarVehiculos',
  // Paralizaciones
  verParalizaciones:     'verParalizaciones',
  crearParalizaciones:   'crearParalizaciones',
  gestionarParalizaciones: 'gestionarParalizaciones',
  eliminarParalizaciones: 'eliminarParalizaciones',
  // Incidencias
  verIncidencias:        'verIncidencias',
  crearIncidencias:      'crearIncidencias',
  revisarIncidencias:    'revisarIncidencias',
  eliminarIncidencias:   'eliminarIncidencias',
  // Tareas
  verTareas:             'verTareas',
  crearTareas:           'crearTareas',
  confirmarTareas:       'confirmarTareas',
  eliminarTareas:        'eliminarTareas',
  // Recambios
  verRecambios:          'verRecambios',
  gestionarRecambios:    'gestionarRecambios',
  eliminarRecambios:     'eliminarRecambios',
  // Proveedores
  verProveedores:        'verProveedores',
  gestionarProveedores:  'gestionarProveedores',
  // Métricas
  verMetricas:           'verMetricas',
  // Configuración
  verConfiguracion:      'verConfiguracion',
  gestionarUsuarios:     'gestionarUsuarios',
  // Audit log
  verAuditLog:           'verAuditLog',
};

// ─── Plantillas por rol ───────────────────────────────────────────────────────
export const PLANTILLAS_ROL = {
  Manager: Object.fromEntries(Object.values(PERMISOS).map(p => [p, true])),

  'Responsable de turno': {
    verDashboard:          true,
    verVehiculos:          true,
    crearVehiculos:        false,
    eliminarVehiculos:     false,
    verParalizaciones:     true,
    crearParalizaciones:   true,
    gestionarParalizaciones: true,
    eliminarParalizaciones: false,
    verIncidencias:        true,
    crearIncidencias:      true,
    revisarIncidencias:    true,
    eliminarIncidencias:   false,
    verTareas:             true,
    crearTareas:           false,
    confirmarTareas:       false,
    eliminarTareas:        false,
    verRecambios:          true,
    gestionarRecambios:    true,
    eliminarRecambios:     false,
    verProveedores:        true,
    gestionarProveedores:  false,
    verMetricas:           false,
    verConfiguracion:      false,
    gestionarUsuarios:     false,
    verAuditLog:           false,
  },

  'Operario de campo': {
    verDashboard:          false,
    verVehiculos:          false,
    crearVehiculos:        false,
    eliminarVehiculos:     false,
    verParalizaciones:     false,
    crearParalizaciones:   false,
    gestionarParalizaciones: false,
    eliminarParalizaciones: false,
    verIncidencias:        true,
    crearIncidencias:      true,
    revisarIncidencias:    false,
    eliminarIncidencias:   false,
    verTareas:             false,
    crearTareas:           false,
    confirmarTareas:       false,
    eliminarTareas:        false,
    verRecambios:          false,
    gestionarRecambios:    false,
    eliminarRecambios:     false,
    verProveedores:        false,
    gestionarProveedores:  false,
    verMetricas:           false,
    verConfiguracion:      false,
    gestionarUsuarios:     false,
    verAuditLog:           false,
  },

  'Operario de taller': {
    verDashboard:          false,
    verVehiculos:          false,
    crearVehiculos:        false,
    eliminarVehiculos:     false,
    verParalizaciones:     false,
    crearParalizaciones:   false,
    gestionarParalizaciones: false,
    eliminarParalizaciones: false,
    verIncidencias:        false,
    crearIncidencias:      false,
    revisarIncidencias:    false,
    eliminarIncidencias:   false,
    verTareas:             true,
    crearTareas:           false,
    confirmarTareas:       true,
    eliminarTareas:        false,
    verRecambios:          false,
    gestionarRecambios:    false,
    eliminarRecambios:     false,
    verProveedores:        false,
    gestionarProveedores:  false,
    verMetricas:           false,
    verConfiguracion:      false,
    gestionarUsuarios:     false,
    verAuditLog:           false,
  },

  'Dirección': {
    verDashboard:          true,
    verVehiculos:          true,
    crearVehiculos:        false,
    eliminarVehiculos:     false,
    verParalizaciones:     true,
    crearParalizaciones:   false,
    gestionarParalizaciones: false,
    eliminarParalizaciones: false,
    verIncidencias:        true,
    crearIncidencias:      false,
    revisarIncidencias:    false,
    eliminarIncidencias:   false,
    verTareas:             true,
    crearTareas:           false,
    confirmarTareas:       false,
    eliminarTareas:        false,
    verRecambios:          true,
    gestionarRecambios:    false,
    eliminarRecambios:     false,
    verProveedores:        true,
    gestionarProveedores:  false,
    verMetricas:           true,
    verConfiguracion:      false,
    gestionarUsuarios:     false,
    verAuditLog:           true,
  },
};